export const defaultNotificationProps = {
	dismissAllLabel: "Descartar todas",
	viewAllLabel: "Ver todas",
	previousLabel: "Anterior",
	readLessLabel: "Ler menos",
	readMoreLabel: "Ler mais",
	title: "Notificações",
	todayLabel: "Hoje",
	yesterdayLabel: "Ontem",
	settingsIconDescription: "Configurações",
	nowText: "Agora",
	emptyStateLabel: "Você não possui novas notificações",
	doNotDisturbLabel: "Não perturbe",
	dismissSingleNotificationIconDescription: "Marcar como lida",
	daysAgoText: (daysAgo) => `${daysAgo} dias atrás`,
	hoursAgoText: (hoursAgo) => `${hoursAgo} horas atrás`,
	minutesAgoText: (minutesAgo) => `${minutesAgo} minutos atrás`,
	minuteAgoText: (minutesAgo) => `${minutesAgo} minuto atrás`,
	monthsAgoText: (monthsAgo) => `${monthsAgo} meses atrás`,
	monthAgoText: (monthAgo) => `${monthAgo} mês atrás`,
	yearAgoText: (yearAgo) => `${yearAgo} ano atrás`,
	yearsAgoText: (yearsAgo) => `${yearsAgo} anos atrás`,
	yesterdayAtText: (yesterdayAt) => `Ontem às ${yesterdayAt}`,
};
