// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "tasks.getAllUsers", input: never, result: User[] } | 
        { key: "version", input: never, result: string },
    mutations: 
        { key: "tasks.createNewUser", input: CreateNewUserParam, result: User },
    subscriptions: never
};

export type CreateNewUserParam = { id: string; name: string }

export type User = { id: string; displayName: string }
